- hosts: puppetmaster
  tasks:
    - name: send bootstrap script
      synchronize:
        src: ../../contrail-infra
        dest: .
    - command: ls
    - command: pwd
    - name: run bootstrap command
      command: ./contrail-infra/tools/bootstrap.sh master
